apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubforge-api
  namespace: hubforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubforge-api
  template:
    metadata:
      labels:
        app: hubforge-api
    spec:
      containers:
        - name: api
          image: ghcr.io/futureedgepro/hubforge-api:latest
          ports:
            - containerPort: 4000
