apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubforge-ui
  namespace: hubforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubforge-ui
  template:
    metadata:
      labels:
        app: hubforge-ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/futureedgepro/hubforge-ui:latest
          ports:
            - containerPort: 3010
