// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/settings/theme": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/devices": {
    params: {};
  };
  "/devices/:id": {
    params: {
      "id": string;
    };
  };
  "/devices/new": {
    params: {};
  };
  "/docs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/settings/theme" | "/dashboard" | "/settings" | "/devices" | "/devices/:id" | "/devices/new" | "/docs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/settings/theme" | "/dashboard" | "/settings" | "/devices" | "/devices/:id" | "/devices/new" | "/docs";
  };
  "routes/_app.settings.theme._index.tsx": {
    id: "routes/_app.settings.theme._index";
    page: "/settings/theme";
  };
  "routes/_app.dashboard._index.tsx": {
    id: "routes/_app.dashboard._index";
    page: "/dashboard";
  };
  "routes/_app.settings._index.tsx": {
    id: "routes/_app.settings._index";
    page: "/settings";
  };
  "routes/_app.devices._index.tsx": {
    id: "routes/_app.devices._index";
    page: "/devices";
  };
  "routes/_app.devices.$id.tsx": {
    id: "routes/_app.devices.$id";
    page: "/devices/:id";
  };
  "routes/_app.devices.new.tsx": {
    id: "routes/_app.devices.new";
    page: "/devices/new";
  };
  "routes/_app.docs._index.tsx": {
    id: "routes/_app.docs._index";
    page: "/docs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.settings.theme._index": typeof import("./app/routes/_app.settings.theme._index.tsx");
  "routes/_app.dashboard._index": typeof import("./app/routes/_app.dashboard._index.tsx");
  "routes/_app.settings._index": typeof import("./app/routes/_app.settings._index.tsx");
  "routes/_app.devices._index": typeof import("./app/routes/_app.devices._index.tsx");
  "routes/_app.devices.$id": typeof import("./app/routes/_app.devices.$id.tsx");
  "routes/_app.devices.new": typeof import("./app/routes/_app.devices.new.tsx");
  "routes/_app.docs._index": typeof import("./app/routes/_app.docs._index.tsx");
};