import path from 'node:path';
import { writeTextFile } from '../lib/fs.js';
import { scaffoldFullTemplatePack } from './full-pack.js';
import type { InitScaffoldOptions } from './types.js';

export async function scaffoldFullPostgresRlsTemplatePack(
  targetDir: string,
  options: InitScaffoldOptions,
): Promise<void> {
  await scaffoldFullTemplatePack(targetDir, options);

  await writeTextFile(
    path.join(targetDir, 'packages', 'db', 'migrations', '0002_enable_rls.sql'),
    postgresRlsMigrationSql(),
  );

  await writeTextFile(path.join(targetDir, 'packages', 'events', 'package.json'), eventsPackageJson());
  await writeTextFile(path.join(targetDir, 'packages', 'events', 'tsconfig.json'), packageTsConfig());
  await writeTextFile(path.join(targetDir, 'packages', 'events', 'src', 'index.ts'), eventsIndexTs());

  await writeTextFile(path.join(targetDir, 'packages', 'workflows', 'package.json'), workflowsPackageJson());
  await writeTextFile(path.join(targetDir, 'packages', 'workflows', 'tsconfig.json'), packageTsConfig());
  await writeTextFile(path.join(targetDir, 'packages', 'workflows', 'src', 'index.ts'), workflowsIndexTs());
  await writeTextFile(path.join(targetDir, 'packages', 'workflows', 'src', 'modules.ts'), workflowsModulesRegistryTs());

  await writeTextFile(path.join(targetDir, 'README.md'), readmeWithRlsNotice(options.projectName));
}

function packageTsConfig(): string {
  return `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "..",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src", "../modules/*/src"]
}
`;
}

function eventsPackageJson(): string {
  const pkg = {
    name: '@hubforge/events',
    version: '0.1.0',
    private: true,
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc --noEmit -p tsconfig.json',
    },
    dependencies: {
      zod: '^3.23.0',
    },
    devDependencies: {
      typescript: '^5.4.0',
    },
  };

  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function eventsIndexTs(): string {
  return `import { z } from 'zod';

export const tenantProvisionedEvent = z.object({
  kind: z.literal('tenant.v1.provisioned'),
  tenantId: z.string(),
  environment: z.string(),
  ts: z.number(),
});

export type TenantProvisionedEvent = z.infer<typeof tenantProvisionedEvent>;
`;
}

function workflowsPackageJson(): string {
  const pkg = {
    name: '@hubforge/workflows',
    version: '0.1.0',
    private: true,
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      build: 'tsc -p tsconfig.json',
      typecheck: 'tsc --noEmit -p tsconfig.json',
    },
    dependencies: {
      '@hubforge/events': 'workspace:*',
    },
    devDependencies: {
      typescript: '^5.4.0',
    },
  };

  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function workflowsIndexTs(): string {
  return `export * from './modules.js';

export function createTenantProvisioningWorkflow(): string[] {
  return [
    'validate-tenant-input',
    'create-tenant-record',
    'apply-tenant-rls-policies',
    'publish-tenant-provisioned-event',
  ];
}
`;
}

function workflowsModulesRegistryTs(): string {
  return `export type TenantModule = {
  id: string;
  name: string;
  route: string;
  tenantScoped?: boolean;
};

export const tenantModules: TenantModule[] = [];
`;
}

function postgresRlsMigrationSql(): string {
  return `-- HubForge Postgres RLS defaults
ALTER TABLE tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE environment ENABLE ROW LEVEL SECURITY;
ALTER TABLE membership ENABLE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation_tenant ON tenant
  USING (id::text = current_setting('app.tenant_id', true));

CREATE POLICY environment_isolation_tenant ON environment
  USING (tenant_id::text = current_setting('app.tenant_id', true));

CREATE POLICY membership_isolation_tenant ON membership
  USING (tenant_id::text = current_setting('app.tenant_id', true));
`;
}

function readmeWithRlsNotice(projectName: string): string {
  return `# ${projectName}

Generated by HubForge CLI using the full-postgres-rls template pack.

## Included baseline

- apps/api (Hono, tenant-aware middleware)
- apps/ui (public site, React Router 7)
- apps/portal (authenticated app, React Router 7)
- apps/ai (FastAPI)
- infra/compose (Docker services)
- packages/api-client (shared API client)
- packages/tenancy (tenant context helpers)
- packages/db (Prisma schema + tracked SQL migrations)
- packages/events (event schemas)
- packages/workflows (workflow defaults)

## Postgres RLS notes

- This template is intended for PostgreSQL only.
- A tracked 0002_enable_rls.sql migration is included for row-level security defaults.
- The generated API baseline is prepared for tenant-aware request context propagation.
`;
}