// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/billing": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/test" | "/dashboard" | "/billing";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/" | "/test";
  };
  "routes/_index.test.ts": {
    id: "routes/_index.test";
    page: "/test";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/dashboard" | "/billing";
  };
  "routes/_app.dashboard._index.tsx": {
    id: "routes/_app.dashboard._index";
    page: "/dashboard";
  };
  "routes/_app.billing._index.tsx": {
    id: "routes/_app.billing._index";
    page: "/billing";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/_index.test": typeof import("./app/routes/_index.test.ts");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.dashboard._index": typeof import("./app/routes/_app.dashboard._index.tsx");
  "routes/_app.billing._index": typeof import("./app/routes/_app.billing._index.tsx");
};