// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/settings/auth-server": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/docs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/settings/auth-server" | "/dashboard" | "/settings" | "/docs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/settings/auth-server" | "/dashboard" | "/settings" | "/docs";
  };
  "routes/_app.settings.auth-server._index.tsx": {
    id: "routes/_app.settings.auth-server._index";
    page: "/settings/auth-server";
  };
  "routes/_app.dashboard._index.tsx": {
    id: "routes/_app.dashboard._index";
    page: "/dashboard";
  };
  "routes/_app.settings._index.tsx": {
    id: "routes/_app.settings._index";
    page: "/settings";
  };
  "routes/_app.docs._index.tsx": {
    id: "routes/_app.docs._index";
    page: "/docs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.settings.auth-server._index": typeof import("./app/routes/_app.settings.auth-server._index.tsx");
  "routes/_app.dashboard._index": typeof import("./app/routes/_app.dashboard._index.tsx");
  "routes/_app.settings._index": typeof import("./app/routes/_app.settings._index.tsx");
  "routes/_app.docs._index": typeof import("./app/routes/_app.docs._index.tsx");
};