// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/settings/auth-server": {
    params: {};
  };
  "/settings/theme": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/assets2": {
    params: {};
  };
  "/assets": {
    params: {};
  };
  "/assets2/:id": {
    params: {
      "id": string;
    };
  };
  "/assets2/new": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/assets/:id": {
    params: {
      "id": string;
    };
  };
  "/assets/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/settings/auth-server" | "/settings/theme" | "/dashboard" | "/settings" | "/assets2" | "/assets" | "/assets2/:id" | "/assets2/new" | "/docs" | "/assets/:id" | "/assets/new";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/settings/auth-server" | "/settings/theme" | "/dashboard" | "/settings" | "/assets2" | "/assets" | "/assets2/:id" | "/assets2/new" | "/docs" | "/assets/:id" | "/assets/new";
  };
  "routes/_app.settings.auth-server._index.tsx": {
    id: "routes/_app.settings.auth-server._index";
    page: "/settings/auth-server";
  };
  "routes/_app.settings.theme._index.tsx": {
    id: "routes/_app.settings.theme._index";
    page: "/settings/theme";
  };
  "routes/_app.dashboard._index.tsx": {
    id: "routes/_app.dashboard._index";
    page: "/dashboard";
  };
  "routes/_app.settings._index.tsx": {
    id: "routes/_app.settings._index";
    page: "/settings";
  };
  "routes/_app.assets2._index.tsx": {
    id: "routes/_app.assets2._index";
    page: "/assets2";
  };
  "routes/_app.assets._index.tsx": {
    id: "routes/_app.assets._index";
    page: "/assets";
  };
  "routes/_app.assets2.$id.tsx": {
    id: "routes/_app.assets2.$id";
    page: "/assets2/:id";
  };
  "routes/_app.assets2.new.tsx": {
    id: "routes/_app.assets2.new";
    page: "/assets2/new";
  };
  "routes/_app.docs._index.tsx": {
    id: "routes/_app.docs._index";
    page: "/docs";
  };
  "routes/_app.assets.$id.tsx": {
    id: "routes/_app.assets.$id";
    page: "/assets/:id";
  };
  "routes/_app.assets.new.tsx": {
    id: "routes/_app.assets.new";
    page: "/assets/new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app.settings.auth-server._index": typeof import("./app/routes/_app.settings.auth-server._index.tsx");
  "routes/_app.settings.theme._index": typeof import("./app/routes/_app.settings.theme._index.tsx");
  "routes/_app.dashboard._index": typeof import("./app/routes/_app.dashboard._index.tsx");
  "routes/_app.settings._index": typeof import("./app/routes/_app.settings._index.tsx");
  "routes/_app.assets2._index": typeof import("./app/routes/_app.assets2._index.tsx");
  "routes/_app.assets._index": typeof import("./app/routes/_app.assets._index.tsx");
  "routes/_app.assets2.$id": typeof import("./app/routes/_app.assets2.$id.tsx");
  "routes/_app.assets2.new": typeof import("./app/routes/_app.assets2.new.tsx");
  "routes/_app.docs._index": typeof import("./app/routes/_app.docs._index.tsx");
  "routes/_app.assets.$id": typeof import("./app/routes/_app.assets.$id.tsx");
  "routes/_app.assets.new": typeof import("./app/routes/_app.assets.new.tsx");
};