// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/" | "/test";
  };
  "routes/_index.test.ts": {
    id: "routes/_index.test";
    page: "/test";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/_index.test": typeof import("./app/routes/_index.test.ts");
};